Update yaml file

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -30,12 +30,12 @@ jobs:
 
       - name: Deploy to Server
         run: |
-          # Define server, project parameters, and repository name
+          # Define server and project parameters
           SERVER_IP="${{ secrets.SERVER_IP }}"
-          USER_NAME="${{ secrets.USER_NAME }}"
+          USER_NAME="mutu"
           FRONTEND_DIR="/var/www/frontend"
-          REPO_NAME="${{ secrets.REPO_NAME }}"  # GitHub repository name as a secret
-          PROJECT_DIR="/home/mutu/project-frontend"  # Specify the project directory
+          PROJECT_DIR="/home/mutu/project-frontend"
+          REPO_NAME="git@github.com:MuratTunc/thy-fly-menu-helper.git"
 
           echo "Deploying frontend to the server..."
           ssh -T -o StrictHostKeyChecking=no $USER_NAME@$SERVER_IP << EOF
@@ -52,7 +52,7 @@ jobs:
             # Check if the project directory exists
             if [ ! -d "$PROJECT_DIR" ]; then
               echo "Directory does not exist. Cloning repository..."
-              git clone git@github.com:MuratTunc/$REPO_NAME.git $PROJECT_DIR
+              git clone $REPO_NAME $PROJECT_DIR
             else
               echo "Directory exists. Pulling latest changes..."
               cd $PROJECT_DIR
@@ -62,6 +62,10 @@ jobs:
 
             # Navigate to the project directory
             cd $PROJECT_DIR
+
+            # Install latest npm version
+            echo "Installing the latest version of npm..."
+            sudo npm install -g npm@latest || { echo "npm install failed!"; exit 1; }
 
             # Install dependencies
             echo "Installing dependencies..."
